### ISSUE TITLE
Push Notification displays Json-Object

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Reflect.UP#133]
@ManuTenorio Whats the status for this issue.

![screenshot_2017-08-07-15-38-23](https://user-images.githubusercontent.com/2682987/29028859-dd262632-7b85-11e7-8bf6-1a1bfa58459c.png)

**Comment by ManuTenorio** [comment]
Hallo Alex,

   Ich freue mich deine Nachricht zu sehen und wissen dass ich Aufgaben zu 
tun habe. 

    Am Mittwoch werde ich reisen um meine Familie zu besuchen. Ab dem 17.08 
werde ich häufiger im Büro arbeiten.

   Schöne Woche noch und wir sehen uns bald.

    Manuel.

**Comment by ManuTenorio** [comment]
Ticket status:

To keep debugging this issue, the first step is make sure that the published version of the Push Notification service uses the actualized version of the script send_notification.php 

![send_notifications](https://user-images.githubusercontent.com/25103016/29670056-ca3abf02-88e5-11e7-8ffb-b19ef921ec09.PNG)

Both variables, &message and &msg must be used to see if the behavior is the expected one.
Instead of the whole JSON object contained in the &message variable, the notification must show only the full name of the course in the smartphone-notification's tray, which is stored in the &msg variable.

**Comment by alekiy** [comment]
the latest version with the changes mentioned above is used :P

**Comment by ManuTenorio** [comment]
different languages encoded as additional data within the URL of the push notification.

TODO:  test with iPhone

**Comment by ManuTenorio** [comment]
Status: iPhone requires specific configuration for off-screen notifications

Problem:  when user clicks on notification, the application is opened, but no message is shown

**Comment by alekiy** [comment]
see #171
