### ISSUE TITLE
No internationalization of texts after feedback submission

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/Reflect.UP#135]
After feedback submission the internationlized strings are printed ignoring the local language.
Maybe it is due to an html encoded string or a missuse of the multilang tag in moodle.

**Comment by ManuTenorio** [comment]
The texts displayed after submission are correctly processed to get the selected language (see the following code snippet from models.js):

![process_text](https://user-images.githubusercontent.com/25103016/29867447-eb504e88-8d7b-11e7-9759-e000727512bf.PNG)

This issue happens when the instructions to add multilanguage tags to moodle contents are not followed. Remember that the contents must be HTML-formated by clicking in this button:

![after_submission](https://user-images.githubusercontent.com/25103016/29867510-1cfaef88-8d7c-11e7-8348-b8453687df2e.PNG)
